#!/bin/bash

TOP_LEVEL=$(git rev-parse --show-toplevel);

if [ -a "$TOP_LEVEL/core/scripts/dev/commit-code-check.sh" ] ; then
  $TOP_LEVEL/core/scripts/dev/commit-code-check.sh --cached
  exit $?;
else
  echo "Can not find $TOP_LEVEL/core/scripts/dev/commit-code-check.sh"
  exit 1
fi
